
# Global options
baseURL = "https://arn-all.github.io/"
canonifyURLs = true
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Arnaud Allera"
enableRobotsTXT = true

# Main menu
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "About me"
    url  = "/about/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/research"
    weight = 3
[[menu.main]]
    name = "Short CV"
    url  = "/cv.pdf"
    weight = 4
#[[menu.main]]
#    name = "Teaching"
#    url  = "/teaching"
#    weight = 2

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Customization options
[params]

    [params.head]
        author = "Arnaud Allera"
        custom_css = "/custom.css"
        description = "Arnaud Allera, Research scientist in Materials Science."
        keywords = ["materials science", "research", "publications", "molecular dynamics"]
    
    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Lora"
        body_font = "Lato"

    [params.colors]
        theme_color = "#333333"
        background_color = "#F2F2F2"
        # text_color = "#3A3335"
        link_color = "#006daa" #ed6a5a

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:arnaud.allera@asnr.fr"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/arn-all"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar"
            url = "https://scholar.google.fr/citations?user=0wWNSagAAAAJ&hl=fr"
            weight = 3
        #[params.social.institution]
        #    name = "My institution"
        #    class = "fas fa-university"
        #    url = ""
        #    weight = 5
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/arnaud-allera-537441277/"
            weight = 6
        [params.social.orcid]
            name = "ORCID iD"
            class = "fab fa-orcid"
            url = "https://orcid.org/0000-0002-8862-8649"
            weight = 7
    # Open Graph settings for social media sharing
    [params.opengraph]
        enable = true
        image = "/avatar.jpg" # Default social sharing image
        locale = "en_US"
        type = "website" # 'article' for blog posts, 'website' for homepage
        # These will be overridden by page-specific front matter
        title = "Arnaud Allera - Materials Science Researcher"
        description = "Arnaud Allera is a materials science researcher specializing in atomic-scale simulations metals."

# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'

